version: '3'
services:
  web:
    container_name: hottofind
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Passw0rd!
      MYSQL_DATABASE: hottofind
      MYSQL_USER: hottofind
      MYSQL_PASSWORD: hottofind

