hottofind:
  container_name: hottofind
  ports:
    - '3000:3000'
    - '3306:3306'
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ./:/app
    - /app/node_modules
    - /app/.next